//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldProperties_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENTAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RENTAL()
        {
            this.RENTALAPPLICATIONs = new HashSet<RENTALAPPLICATION>();
            this.RENTALDOCUMENTs = new HashSet<RENTALDOCUMENT>();
        }
    
        public int RENTALID { get; set; }
        public Nullable<int> PROPERTYID { get; set; }
        public Nullable<int> RENTALSTATUSID { get; set; }
        public Nullable<int> USERID { get; set; }
        public int TERMID { get; set; }
        public Nullable<System.DateTime> RENTALDATESTART { get; set; }
        public Nullable<System.DateTime> RENTALDATEEND { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual PROPERTY PROPERTY { get; set; }
        public virtual TERM TERM { get; set; }
        public virtual RENTALSTATU RENTALSTATU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENTALAPPLICATION> RENTALAPPLICATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENTALDOCUMENT> RENTALDOCUMENTs { get; set; }
    }
}
