//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackGoldProperties_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERLOGINTIMEOUT
    {
        public int USERLOGINTIMEOUTID { get; set; }
        public Nullable<int> USERID { get; set; }
        public int USERLOGINTIMEOUTDESCRIPTION { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
